spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      #discovery:
      #  locator:
      #    enabled: true
      default-filters: 
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
            allowedMethods:
            - GET
            - POST
      routes:
        - id: demo-service
          uri: http://localhost:8090
          predicates:
          - Path=/demo/**
        - id: api-service
          uri: http://localhost:8092
          predicates:
          - Path=/api/**

            

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
      
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway